import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/login.module.scss'
import Logo from '@/public/img/NextGen_TI-logo.png';

import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Contato() {
    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <meta charset="UTF-8" />
            </Head>

            <main>
            <section className={styles.img}>
            <Image className={styles.logoI} src={Logo} alt="Logo" />
               </section>
                <section className={styles.login}>
                    <div className={styles.Tudo}>
                        <div id="loginn">
                            <form method="post" action="">
                                <h1>Login</h1>
                                <div className={styles.Pr1}>
                                    <label for="nome_login"></label>
                                    <input id="nome_login" name="nome_login" required="required" type="text" placeholder="Email" />
                                    <label for="email_login"></label>
                                    <input id="email_login" name="email_login" required="required" type="password" placeholder="Senha" />
                                </div>
                                <div className={styles.Pr2}>
                                    <input type="submit" value="Entrar" />
                                </div>
                                <div className={styles.Pr3}>
                                    <input type="submit" value="Criar" />
                                </div>
                            </form>
                        </div>
                    </div>
                </section>
                <section className={styles.qd}>
           
               </section>
            </main>

        </>
    )
}